name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  TOKEN: '${{ secrets.TOKEN }}'
  ID: '${{ secrets.ID }}'

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Format, Lint, Check Types, test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - run: pnpm install
      - run: pnpm ci

  notification:
    name: Send Discord Notification
    needs: ci
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - run: pnpm install
      - run: pnpm start -m "Latest release on boards-discord" -r "https://github.com/kolaczyn/boards-discord"
